### PR TITLE
fix: shift headings with commonmark AST

### LINKED ISSUE #113: Bug: Code comments are shifted as they where headings
Currently the headings shifting is done by line. Not with an actual markdown parser.

````md
# Heading

```nix
# Comment
```

````

Will result in
````md
### Heading

```nix
### Comment
```

````

Notice that the code comment got shifted as well. To fix this we could use a markdown parser, or use a simple regex to check if we are within a code block.

### PR DESCRIPTION
**Pull request by hsjobeki**
This PR fixes the issue, that the current headings are shifted line wise without taking the context into account.

Leading to issues that shift single line comments in code blocks `# comment` because they look the same as `# heading`

We should use a real commonmark library because code blocks have multiple variants and can also be nested. I am also not sure if there are any other edge cases where a line starts with `# ` and not beeing headings. Any `regex` or other self-cooked algoritms are not desireable due to complexity and maintenance overhead.

Nobody noticed this issue yet; i guess. But as we progress with the migration it is rather ugly and should be fixed by now.  

closes #113

Done:

- [x] Bump fix version
- [x] Add/change unit tests

### CODE REVIEW

File: src/format.rs [hunk 1]
```diff
@@ -62,39 +66,41 @@ pub fn handle_indentation(raw: &str) -> Option<String> {
...
-    let mut rest = String::new();
-    for char in chars {
-        match char {
-            '#' if rest.is_empty() => {
-                // only collect hashes if no other tokens
-                hashes.push(char)
+    // Disable automatic generation of header IDs. nrd will generate them.
+    options.extension.header_ids = None;
+
+    comrak::format_commonmark(root, &ComrakOptions::default(), &mut markdown_output).unwrap();
```
Comment (infinisil) [inline src/format.rs:89]: You're not actually using `options` here :sweat_smile: 

Also, you can construct `options` in the beginning and use it for both parsing and rendering.

File: src/format.rs [hunk 2]
```diff
@@ -62,39 +66,41 @@ pub fn handle_indentation(raw: &str) -> Option<String> {
...
+    let markdown_output = String::from_utf8(markdown_output).unwrap();
+
+    return markdown_output;
```
Comment (infinisil) [inline src/format.rs:92]:
```suggestion
    String::from_utf8(markdown_output).unwrap()
```

Also some justification for the `unwrap`'s would be appreciated

**Review by infinisil — CHANGES_REQUESTED** [review]

File: src/format.rs [hunk 3]
```diff
@@ -62,39 +66,41 @@ pub fn handle_indentation(raw: &str) -> Option<String> {
...
+    // Change some of the default formatting options for better compatibility with nixos-render-docs (nrd).
+    let mut options: Options = ComrakOptions::default();
 
-// Dumb heading parser.
-pub fn handle_heading(line: &str, levels: usize) -> String {
-    let chars = line.chars();
+    // Each newline in the doc-comment sources create a visual line-break in the output,
+    // Making it more intuitive for those who expect a more "what you see is what you get" behavior.
+    // This doesnt conflict with the markdown spec, as it allows for hardbreaks. And allows to save vertical space in doc-comments.
+    options.render.hardbreaks = true;
```
[the remark this answers is not in the document]
Comment (hsjobeki) [reply src/format.rs:84]: Ok we could still introduce this later but maybe. I kind of dislike having double linefeeds for one line break in code files. That increases the filesizes. But i am ok with leaving this out.

**Comment by infinisil** [comment]
(needs a rebase)

**Review by infinisil — APPROVED** [review]
Looking good to me now, thanks!

**Comment by infinisil** [comment]
This seems to have broken the Nixpkgs manual build: https://github.com/NixOS/nixpkgs/pull/302990#issuecomment-2049471406
