### PR TITLE
Fix indentation of structured multi-line comments

### LINKED ISSUE #75: Multiline function attribute argument docs render incorrectly
This file:
```nix
{
  /* Some description */
  f =
    {
      /*
      First line

      Second line
      */
      x,
    }: x;
}
```

Produces this markdown:
```
Some description

structured function argument

: `x`

  : First line

        Second line
```

The second line is indented too much, rendering it as code (only because of the spacing between the lines).

In Nixpkgs I had to unident the entire second paragraph as a workaround: https://github.com/NixOS/nixpkgs/blob/08f615eb1b3c5cf7481996f29c6092c7c891b15b/lib/fileset/default.nix#L72-L76

This could probably use the same fix as in #62

### PR DESCRIPTION
**Pull request by asymmetric**
Closes #75

### CODE REVIEW

File: src/commonmark.rs [hunk 1]
```diff
@@ -41,36 +41,66 @@ pub enum Argument {
...
+///   every other line
+fn handle_indentation(raw: &str) -> String {
+    let result: String = match raw.split_once('\n') {
+        Some((first, rest)) => {
+            format!("{}\n{}", first, textwrap::indent(rest, "  "))
+        }
+        None => raw.into(),
+    };
+
+    result
```
Comment (infinisil) [inline src/commonmark.rs:101]:
```suggestion
    match raw.split_once('\n') {
        Some((first, rest)) => {
            format!("{}\n{}", first, textwrap::indent(rest, "  "))
        }
        None => raw.into(),
    }
```

**Review by infinisil — APPROVED** [review]
Looking good! Only suggested a minor code refactor

File: src/commonmark.rs (hunk 1 above)
Comment (asymmetric) [reply src/commonmark.rs:101]: Right :)
